### ISSUE TITLE
Create Threshold Icons

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Thresholds#1]
See Athena's mockup below. She also mentioned that Jen Bruce would be a good person to reach out to. We can be flexible with the format. The marker Maker may be useful https://test.wim.usgs.gov/markermaker/#/

Athena's mockup:
![image](https://user-images.githubusercontent.com/23640741/118180182-42e36600-b404-11eb-9c79-18423c8963f4.png)

**Comment by lprivette** [comment]
Assigning to Daniel, but feel free to re-assign if need be. if possible, png would be best

**Comment by chaqazarad** [comment]
![Bridge At Risk](https://user-images.githubusercontent.com/85179214/125682249-c8e733f2-1135-4bc7-8fcd-8a70ac828453.png)
![Bridge Flooded](https://user-images.githubusercontent.com/85179214/125682250-e8ffa388-5216-4260-a381-7b4dbfaf1eda.png)
![building flooded](https://user-images.githubusercontent.com/85179214/125682251-0a58ea56-574c-4db4-ad74-5ea13bcb7676.png)
![Car Flooded](https://user-images.githubusercontent.com/85179214/125682252-1b01c7d6-de1d-4871-a6c2-bd2645c862c2.png)
![Path Flooded](https://user-images.githubusercontent.com/85179214/125682254-19e40bbb-7192-419a-a445-e1344c36c7e9.png)
![Site](https://user-images.githubusercontent.com/85179214/125682256-9059c38a-01e1-4cbc-a7fe-3edb03cbe709.png)
![Bank flooded](https://user-images.githubusercontent.com/85179214/125682257-85ce9823-560c-47bd-8b99-4e6513a1d782.png)
