### ISSUE TITLE
Hydrograph with AHPS

### ISSUE THREAD

**Issue by jprokopec** [USGS-WiM/Thresholds#11]
Similar to [FIM](https://fim.wim.usgs.gov/fim/) where you click on a site, the NWIS hydrograph appears. If it is a NWS AHPS site that data will come in and finish the hydrograph. NWS AHPS/USGS Station ID cross-walk-https://hads.ncep.noaa.gov/USGS/ALL_USGS-HADS_SITES.txt

string url = "https://water.weather.gov/ahps2/hydrograph_to_xml.php?gage=" + ahpsID + "&output=xml";

**Comment by lprivette** [comment]
@jprokopec Correct me if I'm wrong with anything I'm saying here.

So in the hydrograph, if a site is also an NWS AHPS Forecast site, we will be adding the predicted trend line to the NWIS gage height line, correct? 
![image](https://user-images.githubusercontent.com/23640741/130523145-959fe95c-d8f0-4447-b218-02d1228a58a3.png)

**Comment by jprokopec** [comment]
@lprivette Correct.

**Comment by Abigail770** [comment]
@lprivette what's the best way to bring in the NWS AHPS data to see if a site is a forecast site? Download the crosswalk and search through the text file to compare the site IDs?

**Comment by lprivette** [comment]
Script now scrapes that text file, identifies the corresponding nws_id, and adds it as a `nws_id` property to each rp. If the site does not have a corresponding nws id it shows up as an empty string: `nws_id: ""`

**Comment by lprivette** [comment]
putting here for reference. Now that the nws id is in the script out put.  i think we can using the url (substituting the id on click) to query forecast values/times https://water.weather.gov/ahps2/hydrograph_to_xml.php?gage=PANK2&output=xml

Now that the time period can be changed, we need to decide how we handle this is if an older date is selected. I don't believe we can pass a time parameter to get predicted values for a past time

**Comment by Abigail770** [comment]
Do we just get the predicted values if they have today's date selected then?  Or if they've selected any date in a certain time period, like the past 3 days for example?
