### ISSUE TITLE
Add "loading" indicator for slower layers

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Thresholds#112]
layers I'm aware of right now that could use this:
- [ ] Flood Elevation Layer

I suggest a "Loading Layers... {spinner}" or something similar in the top left corner of the map when layers are loading. Unless someone has an argument for it, I do not think we want the map to be disabled while the layers load. https://test.wim.usgs.gov/stnweb2/ has this and I believe FEV too.

Mitch has a dope loader that we use in a few other apps. https://fim.wim.usgs.gov/fim/ FIM uses it on site load and on the popup data loading, Might look kinda weird for us though if we're only using it in the top left of the map. 

https://vuetifyjs.com/en/ also has spinners and progress bars.

**Comment by Abigail770** [comment]
The Loading icon for the real time streamgage layer uses a Vuetify progress spinner in the upper left if you wanted something similar to FEV's to build off

**Comment by lprivette** [comment]
Thanks Abby I totally missed that it was already in the app lol, so yes, let's reuse that one for the other layers
