### ISSUE TITLE
Re-design the All Reference Point Icon

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Thresholds#142]
Icon should look related to the active flooding rp icons, but catch the eyes attention as much as they are doing now 

https://wim.usgs.gov/markermaker/#/ can play around here with some round icons maybe?

**Comment by lilyhoutman** [comment]
![image](https://user-images.githubusercontent.com/74278198/130466806-01045b6d-233f-48a3-bf42-3d88fb3f87b9.png)
my inclination would be something like this but curious what daniel thinks too!
