### ISSUE TITLE
Add subsection to Layers panel for "Supporting Layers"

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Thresholds#147]
Call it "Supporting Layers" and put the NWSR, NFHL, and FWW layers under it.

**Comment by lilyhoutman** [comment]
is it weird for the three sections to be "Basemaps", 'Layers", and "Supporting Layers"?
just the repeat of layers seems kinda ??
should the middle one be something else
even "primary layers" might be better"?

**Comment by lprivette** [comment]
I wish we knew what they want to call those sites instead of "Reference Points". I think something more specific than 'primary' could be good. like "Flood Layers", but that wouldn't be entirely accurate since the all RP layer isn't flooding, but would be under that section.

**Comment by lilyhoutman** [comment]
site layers? gage layers?

or just something to be a placeholder for now

**Comment by lprivette** [comment]
yeah just do site layers and we'll get it deployed so that can be included whenever Athena/Jen do their language review.
