### ISSUE TITLE
fix long text on smaller screens

### ISSUE THREAD

**Issue by lilyhoutman** [USGS-WiM/Thresholds#152]
![image](https://user-images.githubusercontent.com/74278198/130467352-4d63cdaf-c98a-4fcf-b810-147e4ea0e9d3.png)
![image](https://user-images.githubusercontent.com/74278198/130467430-645bbbf1-27ff-4e17-b7c7-374a39344273.png)

**Comment by HansVraga** [comment]
Not just a small screen issue; I'm getting it too:
![image](https://user-images.githubusercontent.com/12058013/130482951-b804fdaa-5c54-4dd8-8859-9309bd562d62.png)
