### ISSUE TITLE
Change all RP layer icon in mapper and legend

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Thresholds#167]
should look like 
![image](https://user-images.githubusercontent.com/23640741/130662103-4d13721d-8ce4-4319-b283-33a7604b547a.png)

**Comment by lilyhoutman** [comment]
@lprivette can you clarify where it does NOT look like this icon? i know what it should look like, but i'm confused where you're seeing that is does not

**Comment by lprivette** [comment]
relates to https://github.com/USGS-WiM/Thresholds/issues/142
