### ISSUE TITLE
Create AWS user for Abby and give access to test.wim.usgs.gov bucket

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Thresholds#168]
Abby needs to be able to deploy the Thresholds map to the test bucket. agleason@contractor.usgs.gov

**Comment by aaronstephenson** [comment]
IAM user account created in the WIM Main subaccount, with access to all the basic WIM S3 buckets (test, test-internal, WIM KeePass, and ProjectDataEast). Email sent to Abby with credentials.
