### ISSUE TITLE
Add wim favicon

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Thresholds#17]
I believe the most recent can be found here: https://doimspp.sharepoint.com/sites/GS-UMidWIM/Shared%20Documents/Forms/AllItems.aspx?viewid=144f35a1%2D90d4%2D4ed2%2D9f31%2D521ec6887304&id=%2Fsites%2FGS%2DUMidWIM%2FShared%20Documents%2FDocuments%20%26%20Resources%2FWIM%20Logos

**Comment by Abigail770** [comment]
Should the favicon just go in the index.html file (like this: `<link rel="shortcut icon" id="favicon" type="image/ico" href="assets/favicon-wim.png" />`)? Does it need to be added in anywhere else?

**Comment by lprivette** [comment]
nope that's where we usually put it.
