### ISSUE TITLE
Create Generic AWS User for deleting and deploying to s3 bucket 

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Thresholds#222]
Bucket is wim-thresholds.

Via the python script we'll be deleting and then adding a txt file containing json

**Comment by aaronstephenson** [comment]
IAM user created with API access only (no web console) and no MFA requirement, named "thresholds-s3-user". Credentials are in the WIM KeePass DB.

**Comment by aaronstephenson** [comment]
Just a note that we decided to create a new bucket to contain a static website (thresholds.wim.usgs.gov), anticipating expected future use by non-WIM/public users. Reverse proxied through Toad to S3.
