### ISSUE TITLE
Limit Date selector to dates with valid data

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/Thresholds#228]
Seems I can't get the threshold picture from 1950 (or a few other historic dates). Maybe we should limit the date selector to what NWIS can provide?

**Comment by HansVraga** [comment]
I'm vaguely recalling NWIS had two different endpoints depending on how old the data is - maybe we just follow the 'more recent' one for this?

**Comment by lprivette** [comment]
discussed on call and was decided to set to 01/01/2021: relevant issue https://github.com/USGS-WiM/Thresholds/pull/239
