### ISSUE TITLE
Error in date picker

### ISSUE THREAD

**Issue by lilyhoutman** [USGS-WiM/Thresholds#242]
When I click on the date in the date picker, it displays the current date in very large text rather than immediately letting me select a different date. I think must click the date a second time to change the date

![image](https://user-images.githubusercontent.com/74278198/134672395-4be02b1b-1d8f-4009-b080-32af1145248f.png)

Error occurs in: Chrome, Edge, Firefox

Steps to reproduce the error:
- Click on the date itself (not the calendar). This may be something a lot of users do because they think they can type to change the date
- Large text displays the current date
- Clicking on the current date again allows users to then select a date from the calendar

**Comment by lprivette** [comment]
as a bug or error I'm not really following, what is incorrect in the image?

**Comment by lilyhoutman** [comment]
> as a bug or error I'm not really following, what is incorrect in the image?

sorry, i think your comment in slack answered my question. i thought it was an error to display the current date first, when i would expect users to immediately be brought to the ability to pick a new one. now i understand that the "2021" is the first step of selecting the new date. so i don't think this is an issue actually, though i do still think users may be confused
