### ISSUE TITLE
Script failing to run on Eros server

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Thresholds#290]
I checked AWS and the output.json file was still the old one.

I attempted to check the syslog on WIM1 but it's owner is admin and I can't view it.

**Comment by lprivette** [comment]
I made a small change to the script for a state that had entered RPs but not included a lat long, so if you want we can see if it works tonight

**Comment by lprivette** [comment]
![image](https://user-images.githubusercontent.com/23640741/146207176-0e6c354a-e4d0-459f-90b1-7122c51207c1.png)
still failed today after minor script change (assuming that 'last modified' field in aws would update)

**Comment by aaronstephenson** [comment]
Sorry, just getting time to revisit this. I checked the syslog but didn't see anything. Let's set up logging within your script. Take a look at these [docs](https://docs.python.org/3.9/howto/logging.html#logging-to-a-file). I can help you if you like.

**Comment by lprivette** [comment]
Worked on 1/10 but just checked AWS today and noticed that it had not ran early this morning 
![image](https://user-images.githubusercontent.com/23640741/148968329-3f30fcd2-178f-4002-a4f9-23c8fab93b80.png)

Did we set it up with the recurring cron job in /opt/ or was this just a one off test we had setup?

**Comment by lprivette** [comment]
This can be closed
