### ISSUE TITLE
Search Categories

### ISSUE THREAD

**Issue by jprokopec** [USGS-WiM/Thresholds#323]
The categories 'U.S. State or Territory', 'Cities & Populated Places', 'Streams', etc should be in Spanish.

![Screenshot 2022-11-08 142327](https://user-images.githubusercontent.com/58087084/200667739-8124bfc5-42ac-4e78-8b2a-34eff60788f8.png)

**Comment by lprivette** [comment]
Lets spend a little time seeing if this is possible, but it may not be as this menu is brought in via the USGS/TX search API. I will update this ticket when I have more info.

**Comment by lprivette** [comment]
This text is brought in (not hardcoded by us) via the search API and I am unable to redefine this text. I wonder if we could ask the USGS/TX people to support a Spanish version of the api :)
