### ISSUE TITLE
Current Zoom

### ISSUE THREAD

**Issue by jprokopec** [USGS-WiM/Thresholds#325]
Lat/long are in spanish but 'Current Zoom' is not

![zoom](https://user-images.githubusercontent.com/58087084/200848372-e9649663-2cc6-4371-a77a-6193bf1c14d2.PNG)

**Comment by lprivette** [comment]
![image](https://user-images.githubusercontent.com/23640741/202801621-48849a86-25e8-48d6-9034-4425813ffa97.png)
