### ISSUE TITLE
Create a Lambda Instance for thresholds script

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Thresholds#7]
Already had a brief discussion with Aaron on this. 

I have the api key from Aquarius service desk. DM me when needed.

I'll be writing the script in python.

**Comment by aaronstephenson** [comment]
@lprivette I added you to our Lambda_All user group, so you now have full permissions for lambda and can create your own function. Just don't delete the existing functions ;)

Let me know if you will need any further permissions... you will likely need a role to execute your function, but we can address that when the time comes.

**Comment by lprivette** [comment]
Yay! Thank you Aaron! I'm planning to dig into it first thing tomorrow.
