### ISSUE TITLE
Add location search

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Thresholds#8]
Can either use the tx usgs search api (used in many of our apps such as fev) or if there is a leaflet vue plugin, we can use that.

Let's make it a control on the map

**Comment by Abigail770** [comment]
@lprivette should I stick to the mock-up layout and add the search in the navbar, or make it a control on the map?  Should we include searching by state, zip and all USGS sites (surface water, ground water, atmospheric water, spring, other)?  Any other options?

**Comment by lprivette** [comment]
Sure let try it in the navbar and see how it looks/works. And yes go ahead an include all the options. we can trim it down later if need be
