### ISSUE TITLE
Add Base Flood Elevation Layer

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Thresholds#97]
This will go under the "Layers" expansion panel.

map server: https://hazards.fema.gov/gis/nfhl/rest/services/public/NFHL/MapServer
Arcgis online source: https://www.arcgis.com/home/webmap/viewer.html?url=https%3A%2F%2Fhazards.fema.gov%2Fnfhl%2Frest%2Fservices%2Fpublic%2FNFHL%2FMapServer&source=sd

Include:
- [ ] NFHL Availability
- [ ] FIRM Panels
- [ ] Cross Sections
- [ ] Flood Hazard Boundaries
- [ ] Flood Hazard Zones

@jprokopec let us know if there are any other sublayers we need to include

**Comment by jprokopec** [comment]
Those sublayers look great.
